### ISSUE TITLE
Package works on 1st file only

### ISSUE THREAD

**Issue by vuphan314** [PooSham/atom-scroll-without-moving-cursor#1]
Hi @PooSham:

Thanks for your package!

But scrolling without moving cursor seems not to work on the 2nd, 3rd,... opened files.

Please have a look.

## versions

64-bit Ubuntu 16.10
```
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.12+
git 2.9.3

```

**Comment by vuphan314** [comment]
## Uncaught TypeError: Cannot read property 'setScrollTop' of null

### Steps to Reproduce

1. launch Atom without any opened files
2. open 1st file in Atom (package works now)
3. open 2nd file in Atom (package does not scroll 2nd file)
4. close 1st file
5. (package throws this error)
  - **Atom Version**: 1.13.0
  - **Electron Version**: 1.3.13
  - **System**: Ubuntu 16.10
  - **Thrown From**: [scroll-without-moving-cursor](https://github.com/poosham/atom-scroll-without-moving-cursor) package, v0.3.1


### Stack Trace

Uncaught TypeError: Cannot read property 'setScrollTop' of null

```
At /usr/share/atom/resources/app.asar/src/text-editor-element.js:334

TypeError: Cannot read property 'setScrollTop' of null
    at atom-text-editor.TextEditorElement.setScrollTop (/usr/share/atom/resources/app.asar/src/text-editor-element.js:334:28)
    at Object.scroll (/home/vu/.atom/packages/scroll-without-moving-cursor/lib/scroll-without-moving-cursor.coffee:70:20)
    at Object.scrollDownPage (/home/vu/.atom/packages/scroll-without-moving-cursor/lib/scroll-without-moving-cursor.coffee:45:6)
    at atom-workspace.subscriptions.add.atom.commands.add.editor:page-down-without-moving-cursor (/home/vu/.atom/packages/scroll-without-moving-cursor/lib/scroll-without-moving-cursor.coffee:23:106)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  4x -1:53.2.0 core:page-down (input.hidden-input)
  5x -1:50.8.0 editor:page-down-without-moving-cursor (input.hidden-input)
     -1:48.7.0 core:close (input.hidden-input)
     -1:47.9.0 core:page-down (input.hidden-input)
  4x -1:47.2.0 editor:page-down-without-moving-cursor (input.hidden-input)
  4x -1:44.4.0 editor:page-up-without-moving-cursor (input.hidden-input)
  2x -1:43.2.0 editor:page-down-without-moving-cursor (input.hidden-input)
  5x -1:42.6.0 editor:page-up-without-moving-cursor (input.hidden-input)
     -1:37.1.0 core:page-down (input.hidden-input)
     -1:36.5.0 core:page-up (input.hidden-input)
     -1:35.9.0 editor:page-down-without-moving-cursor (input.hidden-input)
     -0:09.7.0 core:page-down (input.hidden-input)
     -0:08.3.0 core:page-up (input.hidden-input)
     -0:07.3.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -0:05.2.0 core:move-up (input.hidden-input)
     -0:00.1.0 editor:page-down-without-moving-cursor (input.hidden-input)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "closeEmptyWindows": false,
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "tree-view",
      "latex-friend",
      "pdf-view"
    ],
    "projectHome": "~/repos/",
    "telemetryConsent": "no"
  },
  "scroll-without-moving-cursor": {
    "pageScroll": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-sort-projects, v1.6.0 (active)
language-latex, v1.0.0 (active)
latex, v0.42.1 (active)
latex-friend, v0.0.11 (inactive)
MagicPython, v1.0.3 (active)
script, v3.14.0 (inactive)
scroll-without-moving-cursor, v0.3.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (active)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by PooSham** [comment]
Thank you for reporting this! I haven't been using Atom for a long time due to my work involving a lot of .NET requiring me to use Visual Studio/Code :sob:

 I will take a look at it today. I'm still not very comfortable with coffeescript and the Atom API, but I will try.

**Comment by PooSham** [comment]
While fixing the other issue I think I killed two birds with one stone. This bug seems to be fixed now :smiley:
