### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setScrollTop' of null

### ISSUE THREAD

**Issue by SC7639** [PooSham/atom-scroll-without-moving-cursor#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.2 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [scroll-without-moving-cursor](https://github.com/poosham/atom-scroll-without-moving-cursor) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'setScrollTop' of null

```
At C:\Users\SCrossan\AppData\Local\atom\app-1.14.2\resources\app.asar\src\text-editor-element.js:335

TypeError: Cannot read property 'setScrollTop' of null
    at /app.asar/src/text-editor-element.js:335:28)
    at Object.scroll (/packages/scroll-without-moving-cursor/lib/scroll-without-moving-cursor.coffee:70:20)
    at Object.scrollDownLines (/packages/scroll-without-moving-cursor/lib/scroll-without-moving-cursor.coffee:41:6)
    at /packages/scroll-without-moving-cursor/lib/scroll-without-moving-cursor.coffee:21:108)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:51.3.0 editor:scroll-up-without-moving-cursor (input.hidden-input)
     -0:51.1.0 editor:scroll-down-without-moving-cursor (input.hidden-input)
     -0:50.8.0 editor:scroll-up-without-moving-cursor (input.hidden-input)
  2x -0:50.5.0 editor:scroll-down-without-moving-cursor (input.hidden-input)
     -0:50.1.0 editor:scroll-up-without-moving-cursor (input.hidden-input)
     -0:49.9.0 editor:scroll-down-without-moving-cursor (input.hidden-input)
  7x -0:42 core:move-up (input.hidden-input)
  2x -0:40 core:move-down (input.hidden-input)
     -0:38.9.0 editor:scroll-down-without-moving-cursor (input.hidden-input)
     -0:38.2.0 editor:scroll-up-without-moving-cursor (input.hidden-input)
     -0:37.4.0 editor:scroll-down-without-moving-cursor (input.hidden-input)
     -0:37 editor:scroll-up-without-moving-cursor (input.hidden-input)
     -0:36.4.0 editor:consolidate-selections (input.hidden-input)
     -0:36.4.0 core:cancel (input.hidden-input)
     -0:07.8.0 editor:scroll-down-without-moving-cursor (input.hidden-input)
     -0:07.7.0 editor:scroll-up-without-moving-cursor (input.hidden-input)
```

### Non-Core Packages

```
atom-hg 2.0.11 
atom-jade 0.3.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-ternjs 0.17.2 
atom-uikit 1.2.2 
autocomplete-modules 1.6.7 
bottom-dock 0.4.4 
color-picker 2.2.5 
file-icons 2.0.15 
git-plus 7.3.0 
grunt-manager 0.1.16 
hyperclick 0.0.40 
jade-bootstrap3-snippets 0.3.0 
jade-snippets 0.5.0 
language-babel 2.54.1 
language-batch 0.4.0 
language-docker 1.1.7 
language-jade 0.7.2 
language-nginx 0.6.2 
linter 1.11.23 
linter-jshint 3.0.2 
linter-php 1.3.1 
minimap 4.26.8 
nodejs-snippets 2.0.2 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.2.0 
php-integrator-base 2.1.9 
php-integrator-call-tips 1.2.1 
php-integrator-linter 1.3.0 
php-integrator-navigation 1.1.2 
php-integrator-tooltips 1.1.5 
project-manager 3.3.3 
project-plus 0.9.0 
qolor 0.4.1 
react-es6-snippets 0.3.0 
react-snippets 0.7.0 
redux-snippets 0.2.2 
scroll-without-moving-cursor 0.3.1 
snippets-jade 0.2.2 
Stylus 3.1.0 
tortoise-hg 1.0.0 
```

**Comment by PooSham** [comment]
Because of my current work that involves a lot of .NET development, I haven't been using atom lately and haven't had time to care about this project. I will take a look at it today, but since I'm pretty bad with coffeescript and the Atom API, I can't promise anything. 

Thanks for reporting!

**Comment by PooSham** [comment]
So the issue seemed only to appear for me if I first closed all my tabs and then opened a file again. I found the error in the code that caused this, so please update to the latest version. In your bug report however it seemed like you were always having this error, so I'm not sure if it's a Windows-specific problem (I run Ubuntu). Anyways, I'll close this for now and might reopen it if you still experience problems.
