### ISSUE TITLE
Uncaught TypeError: this.editorElement.getHeight is not a function

### ISSUE THREAD

**Issue by vuphan314** [PooSham/atom-scroll-without-moving-cursor#3]
Hi @PooSham:

Thanks for your response in #1!

However, the following new error was thrown. Please have a look if you have more time.

### Steps to Reproduce

1. open a text file in `Atom`
2. do `page-down-without-moving-cursor`

### Versions

- **Atom**: 1.14.4 x64
- **Electron**: 1.3.13
- **OS**: Ubuntu 16.10
- **Thrown From**: [scroll-without-moving-cursor](https://github.com/poosham/atom-scroll-without-moving-cursor) package 0.3.4

### Stack Trace

Uncaught TypeError: this.editorElement.getHeight is not a function

```
At /home/vu/Dropbox/atom/packages/scroll-without-moving-cursor/lib/scroll-without-moving-cursor.coffee:66

TypeError: this.editorElement.getHeight is not a function
    at Object.calculatePageScrollPixels (/packages/scroll-without-moving-cursor/lib/scroll-without-moving-cursor.coffee:66:29)
    at Object.scrollDownPage (/packages/scroll-without-moving-cursor/lib/scroll-without-moving-cursor.coffee:45:25)
    at /packages/scroll-without-moving-cursor/lib/scroll-without-moving-cursor.coffee:22:106)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/app.asar/node_modules/command-palette/lib/command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at /app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:47.5.0 editor:page-down-without-moving-cursor (input.hidden-input)
  2x -0:22.1.0 core:cancel (a.stack-toggle)
     -0:17.2.0 command-palette:toggle (input.hidden-input)
  2x -0:16 core:backspace (input.hidden-input)
  2x -0:12.3.0 core:move-down (input.hidden-input)
     -0:10.9.0 core:confirm (input.hidden-input)
     -0:10.8.0 editor:page-down-without-moving-cursor (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
atom-sort-projects 1.6.0 
language-batch 0.4.0 
language-latex 1.0.0 
latex 0.42.3 
latex-friend 0.0.11 
MagicPython 1.0.7 
script 3.14.1 
scroll-without-moving-cursor 0.3.4 
sort-lines 0.14.0 
```

**Comment by PooSham** [comment]
lol I was sure I fixed that but I got confused by git and apm and for some reason I went back in the code history. Well.. should be fixed now. Thanks for reporting

**Comment by vuphan314** [comment]
@PooSham:

It works now! Thanks a lot!

--Vu
